### ISSUE TITLE
DCR feat: improve the error message on duplicate client_id

### ISSUE THREAD

**Issue by HemantKMehta** [JanssenProject/jans-auth-server#132]
It is about improving the error message by giving specific error while running DCR flow for same client (duplicate).

**Comment by yuriyz** [comment]
Our default behavior fits to what FAPI requires -> standard messages and as less details in error response as possible (they rejected certification due to `reason` field and not standard errors which we used to provide very specific reason of failure. It seems FAPI forces engineer look into logs to understand real cause of failure.)

Actually we should provide ability to specify both error and error message in custom registration script during both creation and update. It will allow specify errors according to customer and not changing server code. Created ticket to provide such feature: https://github.com/JanssenProject/jans-auth-server/issues/133

After it's fixed this ticket will be solved by changing custom registration script.

**Comment by yuriyz** [comment]
Assigned to @maduvena , she will update custom script after #133 is implemented.

**Comment by yuriyz** [comment]
@maduvena #133 is implemented, you can fix this ticket in custom script.

**Comment by yuriyz** [comment]
@HemantKMehta do we still need it ?

**Comment by Milton-Ch** [comment]
Since there is a way to set error and error message, we don't require it anymore.
cc: @HemantKMehta
