### ISSUE TITLE
MTLS for registration endpoint

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans-auth-server#152]
## Describe the issue

We need to provide ability turn on/off MLTS for registration endpoint : 
- add configuration property `dcrAuthorizationWithMTLS` (`false` by default but `true` for openbanking)
- if true invoke `MTLSService`
- provide apache config for it

From docs
```
The TPP must only present the SSA to an ASPSP over a mutually authenticated TLS channel using a certificate issued by the OB. In this case, the combination of possession of the SSA, the possession of private keys referenced in the SSA and ability to present it over a channel that can be validated as belonging to the same TPP organization, is a strong barrier for attackers.
```

https://openbanking.atlassian.net/wiki/spaces/DZ/pages/36667724/OpenBanking+OpenID+Dynamic+Client+Registration+Specification+-+v1.0.0-rc2

**Comment by Milton-Ch** [comment]
After digging more about this requirement, these are my conclusions:
1. We need MTLS set up for `/register`, client certificate doesn't need anything special, the definition says:
> certificate chains to the OpenBanking certificate authority and is not revoked
Based on this definition, it only means that we have to configure Apache2 to request client certificate and validate it properly with acceptable issuers. This is something that Apache2 already does, but we haven't added MTLS in `/register` endpoint, in this case we have to add something like this to that path:
```
SSLVerifyClient  require
        SSLVerifyDepth 10
        SSLOptions +StdEnvVars +StrictRequire +ExportCertData
```

**Comment by yuriyz** [comment]
Problem is that `MTLSService` will not be run. Adding Apache configuration is part of the solution. We need property to let MTLSService run for `/register` or skip it. (We can't enforce it all the time). Also note for OB we have `dcrAuthorizationWithClientCredentials` which enforced client credentials for `/register`.

**Comment by Milton-Ch** [comment]
Yeah, I think idea is not to authenticate client based on client certificate like `/token` or similar endpoints, in this special case specs say that we only have to validate that the client certificate chains to one of the OB certificate authority and it's not revoked, these 2 checks are processed by Apache. I think after Apache check, Jans AS will skip MTLSService because there is no client registered and then client registration is processed accordingly as we have today.
I assume this behavior is because TPP will get client certification and SSA from OB first, then register the client in ASPSP, at this point ASPSP will be able to validate client certificate but not client info because this info is not in the DB, and finally ASPSP will register client and then verify all HTTP calls to `/token` or similar endpoints properly.

**Comment by yuriyz** [comment]
Are you talking about this MTLS spec or something else ? https://datatracker.ietf.org/doc/html/rfc8705

True, it's not db during registration, so we have to run it againt entry which we are registering in current request. It's easy because it can be passed explicitly in `processMTLS`. Can you show links or something that says that we can skip some parts of MTLS spec during `/register` MTLS?

**Comment by Milton-Ch** [comment]
Yes, MTLS in those specs. I was following master version about specs, they are here: https://bitbucket.org/openid/obuk/src/4630771db004da59992fb201641f5c4ff2c881f1/uk-openbanking-registration-profile.md?at=master&fileviewer=file-view-default
Section: "Automated Client Registration"
> The TPP must only present the SSA to an ASPSP over a mutually authenticated TLS channel using a certificate issued by the OB. In this case, the combination of possession of the SSA, the possession of private keys referenced in the SSA and ability to present it over a channel that can be validated as belonging to the same TPP organization, is a strong barrier for attackers.

Also point "Client Registration Endpoint"
> If an ASPSP supports automated client registration, the ASPSP MUST operate an [RFC7591] compliant registration endpoint. * The client registration endpoint MUST be protected by transport-layer security (TLS 1.2 or better) * The transport layer MUST be mutually authenticated using certificates chaining to the OpenBanking certificate authority * The ASPSP registration endpoint MUST accept HTTP POST messages with request parameters encoded in the entity body using the "application/jwt" content-type. * The ASPSP registration endpoint SHOULD accept registration attempts from any mutually authenticated channel whose certificate chains to the OpenBanking certificate authority and is not revoked.

**Comment by Milton-Ch** [comment]
Using information from the request doesn't look to be specified in specs, also I think idea of authenticating client based on request info will always pass, doesn't make sense because client could send anything. I guess main idea here is add a security layer using client certificate, but it doesn't mean adding authn based on request info.

**Comment by yuriyz** [comment]
MTLS means that certificate is bound to client. My question is if we ignore is it still MTLS? For me it sounds logical if we check whether its bound to client or not. It means that you can NOT send any client in registration request. Only the one which is bound to that particular certificate.

**Comment by Milton-Ch** [comment]
New flag `dcrAuthorizationWithMTLS` added and validation between client certificate and `tls_client_auth_subject_dn` field was introduced.
