### ISSUE TITLE
ci: quality checks for jans-auth-server are not run

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans-auth-server#196]
## Describe the issue

Quality checks are not run because git action build failed. However jenkins shows that build is successful. Sounds as some type of mis-configuration.

https://github.com/JanssenProject/jans-auth-server/runs/3530773576?check_suite_focus=true

![image](https://user-images.githubusercontent.com/2013070/132298387-f5586984-fb75-4899-b79c-d1a0a47b983b.png)

**Comment by ossdhaval** [comment]
Yes, I saw this yesterday. 
Currently, build during Github action runs like local build (i.e with m2 caching etc) and not like CI build (from scratch without m2).
Making changes to give Github action builds a clean start.

**Comment by Milton-Ch** [comment]
Hey guys @ossdhaval @yuriyz @moabu Looks like this issue is still present, should I do something different or how should I proceed?
![Selection_1044](https://user-images.githubusercontent.com/86965029/132947981-8867a534-37fe-48a2-a354-10f96efc9be3.png)
https://github.com/JanssenProject/jans-auth-server/pull/175/checks?check_run_id=3574917433

**Comment by yuriyz** [comment]
Looks like fixed already, all 11 checks inclusing sonar and snyk are passed.

![image](https://user-images.githubusercontent.com/2013070/132959856-c1c21a71-de47-4a18-8c76-ab494e522166.png)

**Comment by Milton-Ch** [comment]
Yeah, fixed, thanks!
