### ISSUE TITLE
Replace Jython2

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans-auth-server#80]
Jython currently has no real plans to support Python3. Most of the code is marked legacy due to Jython which is currently only supporting python2 and uses CPython 2.7 which has been depreciated since Jan 1st 2020. A solution needs to be made by finding a viable alternative.

https://talvi.net/a-brief-overview-of-python-java-bridges-in-2020.html

**Comment by yurem** [comment]
Jython2 is not depends on Python2. It's independent framework which just based on Python2 langiage. It's has own release schedule which not conform to python/cpython. Hence instead of replacing well working solution we need to do research to find second approach. It should provides similar to Jython functionality.

**Comment by nynymike** [comment]
I don't agree with replacing Jython. We already have other issues to support alternate syntaxes for scripting, like Javascript, or to enable the use of Java classes directly.
